/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.math.graphic.forms.shapes;

import ec.edu.espe.math.conversion.Conversion;
import ec.edu.espe.math.geometry.shapes.triangles.EquilateralTriangle;
import ec.edu.espe.math.geometry.shapes.triangles.IsocescelesTriangle;
import ec.edu.espe.math.geometry.shapes.triangles.ObtuseAngleTriangle;
import ec.edu.espe.math.geometry.shapes.triangles.RightAngleTriangle;
import ec.edu.espe.math.geometry.shapes.triangles.ScaleneTriangle;
import ec.edu.espe.math.geometry.shapes.triangles.Triangle;
import ec.edu.espe.math.graphic.forms.text.ShapesCatalog;
import ec.edu.espe.math.graphic.utils.PrinterUtil;
import ec.edu.espe.util.UnitConstants;
import javax.swing.JOptionPane;

/**
 *
 * @author SONY
 */
public class ShapeTriangle extends javax.swing.JFrame {

    /**
     * Creates new form ShapeCircular
     */
    public ShapeTriangle() {
        initComponents();
        shapeSelection.addItem(ShapesCatalog.EQUILATERAL_TRIANGLE);
        shapeSelection.addItem(ShapesCatalog.ISOCELES_TRIANGLE);
        shapeSelection.addItem(ShapesCatalog.OBTUSANGLE_TRIANGLE);
        
        shapeSelection.addItem(ShapesCatalog.RIGHT_ANGLE_TRIANGLE);
        shapeSelection.addItem(ShapesCatalog.SCALENE_TRIANGLE);
        
        
         unitIn.addItem(UnitConstants.MM);
        unitIn.addItem(UnitConstants.CM);
        unitIn.addItem(UnitConstants.DM);
        unitIn.addItem(UnitConstants.M);
        unitIn.addItem(UnitConstants.DAM);
        unitIn.addItem(UnitConstants.HM);
        unitIn.addItem(UnitConstants.KM);

        unitOut.addItem(UnitConstants.MM);
        unitOut.addItem(UnitConstants.CM);
        unitOut.addItem(UnitConstants.DM);
        unitOut.addItem(UnitConstants.M);
        unitOut.addItem(UnitConstants.DAM);
        unitOut.addItem(UnitConstants.HM);
        unitOut.addItem(UnitConstants.KM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        shapeSelection = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblLado1 = new javax.swing.JLabel();
        txtVal1 = new javax.swing.JTextField();
        lblLado2 = new javax.swing.JLabel();
        txtVal2 = new javax.swing.JTextField();
        lblLado3 = new javax.swing.JLabel();
        txtVal3 = new javax.swing.JTextField();
        unitIn = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPerimeter = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        unitOut = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Triangle");

        shapeSelection.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        shapeSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shapeSelectionActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblLado1.setText("Lado1");

        lblLado2.setText("Lado2");

        lblLado3.setText("Lado3");

        unitIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitInActionPerformed(evt);
            }
        });

        jLabel8.setText("Units");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLado2)
                        .addComponent(lblLado1)
                        .addComponent(lblLado3))
                    .addComponent(jLabel8))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitIn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVal3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVal1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVal2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado1)
                    .addComponent(txtVal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado2)
                    .addComponent(txtVal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado3)
                    .addComponent(txtVal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setText("Perimeter");

        jLabel4.setText("Area");

        unitOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitOutActionPerformed(evt);
            }
        });

        jLabel7.setText("Units");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPerimeter, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(txtArea))
                    .addComponent(unitOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ATRAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(shapeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shapeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shapeSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shapeSelectionActionPerformed
        if (shapeSelection.getSelectedItem().equals(ShapesCatalog.EQUILATERAL_TRIANGLE)) {
            txtVal2.setEnabled(false);
            txtVal3.setEnabled(false);
            PrinterUtil.setLabels(lblLado1, lblLado2, lblLado3, "Side", "       ", "      ");
        } else if (shapeSelection.getSelectedItem().equals(ShapesCatalog.ISOCELES_TRIANGLE)) {
            txtVal2.setEnabled(true);
            txtVal3.setEnabled(false);
            PrinterUtil.setLabels(lblLado1, lblLado2, lblLado3, "Base", "Height", "        ");
        } else if (shapeSelection.getSelectedItem().equals(ShapesCatalog.OBTUSANGLE_TRIANGLE)) {
            txtVal2.setEnabled(true);
            txtVal3.setEnabled(true);
            PrinterUtil.setLabels(lblLado1, lblLado2, lblLado3, "Side 1", "Side 2", "Side 3");
        } else if (shapeSelection.getSelectedItem().equals(ShapesCatalog.RIGHT_ANGLE_TRIANGLE)) {
            txtVal2.setEnabled(true);
            txtVal3.setEnabled(false);
            PrinterUtil.setLabels(lblLado1, lblLado2, lblLado3, "Base", "Height", "      ");
         } else if (shapeSelection.getSelectedItem().equals(ShapesCatalog.SCALENE_TRIANGLE)) {
            txtVal2.setEnabled(true);
            txtVal3.setEnabled(true);
            PrinterUtil.setLabels(lblLado1, lblLado2, lblLado3, "Side 1", "Side 2", "Side 3");        }
    }//GEN-LAST:event_shapeSelectionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Triangle triangle=null;
            Conversion conv=new Conversion();

            if(shapeSelection.getSelectedItem().equals(ShapesCatalog.EQUILATERAL_TRIANGLE)){
                triangle=new EquilateralTriangle(Float.parseFloat(txtVal1.getText()));
            }
            else if(shapeSelection.getSelectedItem().equals(ShapesCatalog.ISOCELES_TRIANGLE)){
                triangle=new IsocescelesTriangle(Float.parseFloat(txtVal1.getText()),Float.parseFloat(txtVal2.getText()));
            }
            else if(shapeSelection.getSelectedItem().equals(ShapesCatalog.OBTUSANGLE_TRIANGLE)){
                triangle=new ObtuseAngleTriangle(Float.parseFloat(txtVal1.getText()),Float.parseFloat(txtVal2.getText()),Float.parseFloat(txtVal3.getText()));
            }
            else if(shapeSelection.getSelectedItem().equals(ShapesCatalog.RIGHT_ANGLE_TRIANGLE)){
                triangle=new RightAngleTriangle(Float.parseFloat(txtVal1.getText()),Float.parseFloat(txtVal2.getText()));
            }
             else if(shapeSelection.getSelectedItem().equals(ShapesCatalog.SCALENE_TRIANGLE)){
                triangle=new ScaleneTriangle(Float.parseFloat(txtVal1.getText()),Float.parseFloat(txtVal2.getText()),Float.parseFloat(txtVal3.getText()));
            }
            ec.edu.espe.math.graphic.utils.PrinterUtil.printResults(txtArea, txtPerimeter, conv.convertSquare(triangle.area(),unitIn.getSelectedItem().toString(),unitOut.getSelectedItem().toString()), conv.convert(triangle.perimeter(),unitIn.getSelectedItem().toString(),unitOut.getSelectedItem().toString()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "INGRESE DATOS VALIDOS");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       MenuShape menuShape=new MenuShape();
       menuShape.setLocationRelativeTo(this);
       menuShape.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void unitInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitInActionPerformed
        // lblUnits.setText(unitIn.getSelectedItem().toString());
    }//GEN-LAST:event_unitInActionPerformed

    private void unitOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitOutActionPerformed
        // Conversion conv= new Conversion();
        //  conv.convert(Float.parseFloat(txtPerimeter.getText()), , unit2)
    }//GEN-LAST:event_unitOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShapeTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShapeTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShapeTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShapeTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapeTriangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLado1;
    private javax.swing.JLabel lblLado2;
    private javax.swing.JLabel lblLado3;
    private javax.swing.JComboBox<String> shapeSelection;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtPerimeter;
    private javax.swing.JTextField txtVal1;
    private javax.swing.JTextField txtVal2;
    private javax.swing.JTextField txtVal3;
    private javax.swing.JComboBox<String> unitIn;
    private javax.swing.JComboBox<String> unitOut;
    // End of variables declaration//GEN-END:variables
}
